COMMAND_TIMEOUT: 0
ENCODER_ZERO: 1
AXIS_OFFSET: 2
REPORT_RATE: 3
PPID_Kp: 4
PPID_Ki: 5
PPID_Kd: 6
PPID_deadzone: 8
PPID_dUmax: 10
VPID_Kp: 12
VPID_Ki: 13
VPID_Kd: 14
VPID_deadzone: 16
VPID_dUmax: 18
CPID_Kp: 20
CPID_Ki: 21
CPID_Kd: 22
CPID_deadzone: 24
CPID_dUmax: 26
IIR_VALUE_CURMEAS: 28
IIR_VALUE_VELMEAS: 29
IIR_VALUE_PPIDU: 30
IIR_VALUE_VPIDU: 31
IIR_VALUE_CPIDU: 32
MIN_POSITION: 35
MAX_POSITION: 36
MIN_VELOCITY: 37
MAX_VELOCITY: 38
MIN_CURRENT: 39
MAX_CURRENT: 40
MIN_DUTY: 41
MAX_DUTY: 47
OVERHEAT_TEMPERATURE: 80
NO_OVERHEAT_TEMPERATURE: 81
PARAM_INVERT_AXIS: 82
PARAM_INVERT_ENCODER: 83
PARAM_ENCODER_FILTER_WINDOW: 84